# Universal fish vars — source of truth for tide preferences + user paths.
# Fish's $XDG_CONFIG_HOME/fish/fish_variables is gitignored because
# it's owned by fish and churns constantly (prompt cache, counters).
# Edit this file, re-login, and every machine picks up the change.

set -Ux fish_user_paths /home/mdaum/.local/bin
set -Ux tide_aws_bg_color FF9900
set -Ux tide_aws_color 232F3E
set -Ux tide_aws_icon 
set -Ux tide_character_color 5FD700
set -Ux tide_character_color_failure FF0000
set -Ux tide_character_icon ❯
set -Ux tide_character_vi_icon_default ❮
set -Ux tide_character_vi_icon_replace ▶
set -Ux tide_character_vi_icon_visual V
set -Ux tide_cmd_duration_bg_color C4A000
set -Ux tide_cmd_duration_color 000000
set -Ux tide_cmd_duration_decimals 0
set -Ux tide_cmd_duration_icon 
set -Ux tide_cmd_duration_threshold 3000
set -Ux tide_context_always_display false
set -Ux tide_context_bg_color 444444
set -Ux tide_context_color_default D7AF87
set -Ux tide_context_color_root D7AF00
set -Ux tide_context_color_ssh D7AF87
set -Ux tide_context_hostname_parts 1
set -Ux tide_crystal_bg_color FFFFFF
set -Ux tide_crystal_color 000000
set -Ux tide_crystal_icon 
set -Ux tide_direnv_bg_color D7AF00
set -Ux tide_direnv_bg_color_denied FF0000
set -Ux tide_direnv_color 000000
set -Ux tide_direnv_color_denied 000000
set -Ux tide_direnv_icon ▼
set -Ux tide_distrobox_bg_color FF00FF
set -Ux tide_distrobox_color 000000
set -Ux tide_distrobox_icon 󰆧
set -Ux tide_docker_bg_color 2496ED
set -Ux tide_docker_color 000000
set -Ux tide_docker_default_contexts default colima
set -Ux tide_docker_icon 
set -Ux tide_elixir_bg_color 4E2A8E
set -Ux tide_elixir_color 000000
set -Ux tide_elixir_icon 
set -Ux tide_gcloud_bg_color 4285F4
set -Ux tide_gcloud_color 000000
set -Ux tide_gcloud_icon 󰊭
set -Ux tide_git_bg_color 4E9A06
set -Ux tide_git_bg_color_unstable C4A000
set -Ux tide_git_bg_color_urgent CC0000
set -Ux tide_git_color_branch 000000
set -Ux tide_git_color_conflicted 000000
set -Ux tide_git_color_dirty 000000
set -Ux tide_git_color_operation 000000
set -Ux tide_git_color_staged 000000
set -Ux tide_git_color_stash 000000
set -Ux tide_git_color_untracked 000000
set -Ux tide_git_color_upstream 000000
set -Ux tide_git_icon 
set -Ux tide_git_truncation_length 24

set -Ux tide_go_bg_color 00ACD7
set -Ux tide_go_color 000000
set -Ux tide_go_icon 
set -Ux tide_java_bg_color ED8B00
set -Ux tide_java_color 000000
set -Ux tide_java_icon 
set -Ux tide_jobs_bg_color 444444
set -Ux tide_jobs_color 4E9A06
set -Ux tide_jobs_icon 
set -Ux tide_jobs_number_threshold 1000
set -Ux tide_kubectl_bg_color 326CE5
set -Ux tide_kubectl_color 000000
set -Ux tide_kubectl_icon 󱃾
set -Ux _tide_left_items os pwd git newline character
set -Ux tide_left_prompt_frame_enabled true
set -Ux tide_left_prompt_items os pwd git newline character
set -Ux tide_left_prompt_prefix 
set -Ux tide_left_prompt_separator_diff_color 
set -Ux tide_left_prompt_separator_same_color 
set -Ux tide_left_prompt_suffix 
set -Ux tide_nix_shell_bg_color 7EBAE4
set -Ux tide_nix_shell_color 000000
set -Ux tide_nix_shell_icon 
set -Ux tide_node_bg_color 44883E
set -Ux tide_node_color 000000
set -Ux tide_node_icon 
set -Ux tide_os_bg_color D4D4D4
set -Ux tide_os_color E95420
set -Ux tide_os_icon 
set -Ux tide_php_bg_color 617CBE
set -Ux tide_php_color 000000
set -Ux tide_php_icon 
set -Ux tide_private_mode_bg_color F1F3F4
set -Ux tide_private_mode_color 000000
set -Ux tide_private_mode_icon 󰗹
set -Ux tide_prompt_add_newline_before false
set -Ux tide_prompt_color_frame_and_connection 444444
set -Ux tide_prompt_color_separator_same_color 949494
set -Ux tide_prompt_icon_connection ' '
set -Ux tide_prompt_min_cols 34
set -Ux tide_prompt_pad_items true
set -Ux tide_prompt_transient_enabled true
set -Ux tide_pulumi_bg_color F7BF2A
set -Ux tide_pulumi_color 000000
set -Ux tide_pulumi_icon 
set -Ux tide_pwd_bg_color 3465A4
set -Ux tide_pwd_color_anchors E4E4E4
set -Ux tide_pwd_color_dirs E4E4E4
set -Ux tide_pwd_color_truncated_dirs BCBCBC
set -Ux tide_pwd_icon 
set -Ux tide_pwd_icon_home 
set -Ux tide_pwd_icon_unwritable 
set -Ux tide_pwd_markers .bzr .citc .git .hg .node-version .python-version .ruby-version .shorten_folder_marker .svn .terraform Cargo.toml composer.json CVS go.mod package.json build.zig
set -Ux tide_python_bg_color 444444
set -Ux tide_python_color 00AFAF
set -Ux tide_python_icon 󰌠
set -Ux _tide_right_items status cmd_duration context jobs direnv node python rustc terraform aws time
set -Ux tide_right_prompt_frame_enabled false
set -Ux tide_right_prompt_items status cmd_duration context jobs direnv node python rustc java php pulumi ruby go gcloud kubectl distrobox toolbox terraform aws nix_shell crystal elixir zig time
set -Ux tide_right_prompt_prefix 
set -Ux tide_right_prompt_separator_diff_color 
set -Ux tide_right_prompt_separator_same_color 
set -Ux tide_right_prompt_suffix 
set -Ux tide_ruby_bg_color B31209
set -Ux tide_ruby_color 000000
set -Ux tide_ruby_icon 
set -Ux tide_rustc_bg_color F74C00
set -Ux tide_rustc_color 000000
set -Ux tide_rustc_icon 
set -Ux tide_shlvl_bg_color 808000
set -Ux tide_shlvl_color 000000
set -Ux tide_shlvl_icon 
set -Ux tide_shlvl_threshold 1
set -Ux tide_status_bg_color 2E3436
set -Ux tide_status_bg_color_failure CC0000
set -Ux tide_status_color 4E9A06
set -Ux tide_status_color_failure FFFF00
set -Ux tide_status_icon ✔
set -Ux tide_status_icon_failure ✘
set -Ux tide_terraform_bg_color 800080
set -Ux tide_terraform_color 000000
set -Ux tide_terraform_icon 󱁢
set -Ux tide_time_bg_color D3D7CF
set -Ux tide_time_color 000000
set -Ux tide_time_format '%T'
set -Ux tide_toolbox_bg_color 613583
set -Ux tide_toolbox_color 000000
set -Ux tide_toolbox_icon 
set -Ux tide_vi_mode_bg_color_default 949494
set -Ux tide_vi_mode_bg_color_insert 87AFAF
set -Ux tide_vi_mode_bg_color_replace 87AF87
set -Ux tide_vi_mode_bg_color_visual FF8700
set -Ux tide_vi_mode_color_default 000000
set -Ux tide_vi_mode_color_insert 000000
set -Ux tide_vi_mode_color_replace 000000
set -Ux tide_vi_mode_color_visual 000000
set -Ux tide_vi_mode_icon_default D
set -Ux tide_vi_mode_icon_insert I
set -Ux tide_vi_mode_icon_replace R
set -Ux tide_vi_mode_icon_visual V
set -Ux tide_zig_bg_color F7A41D
set -Ux tide_zig_color 000000
set -Ux tide_zig_icon 
set -Ux VIRTUAL_ENV_DISABLE_PROMPT true
